base_version: SHiELD/PIRE-like
forcing: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/reference/2024-06-19-vcm-fv3config/data/base_forcing/SHiELD/v1.0-perpetual-2xCO2-1997-SOM/C96  # We will simply not use the SOM forcing files, but all the other forcing files are the same
field_table: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/reference/2024-06-19-vcm-fv3config/config/field_table/TKE-EDMF/v1.1/field_table  # Required for the TKE-EDMF scheme
orographic_forcing: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/reference/2024-06-19-vcm-fv3config/data/orographic_data/v1.2
initial_conditions: PLACEHOLDER
namelist:
  atmos_model_nml:
    fdiag: 6.0  # Required for outputting physics diagnostics every six hours
    blocksize: 16  # Evenly distribute blocks with a 12x12 layout
  coupler_nml:
    calendar: gregorian
    days: 0
    hours: 0
    minutes: 0
    seconds: 0
    months: 1
    force_date_from_namelist: true
    current_date:
    - 2019
    - 10
    - 1
    - 0
    - 0
    - 0
  diag_manager_nml:
    flush_nc_files: true
    mix_snapshot_average_fields: true  # Harmonize time labels of interval average and snapshot diagnostics
  external_ic_nml:
    levp: 79  # The initial condition we created has 79 vertical levels
  fv_core_nml:
    npx: 97
    npy: 97
    layout:  # Use 864 cores to speed wall clock time of simulation
    - 12
    - 12
    k_split: 2
    n_split: 6
    kord_wz: 9  # There was a minor bug found in the PIRE codebase for kord_wz = -9, so Lucas recommends using kord_wz = 9
    external_ic: false  # Required for starting from restart files
    nggps_ic: false  # Required for starting from restart files
    make_nh: false  # Required for starting from restart files
    mountain: true  # Required for starting from restart files
    warm_start: true  # Required for starting from restart files
    na_init: 0  # Required for starting from restart files
  fv_grid_nml:
    grid_file: INPUT/grid_spec.nc  # Use a prescribed grid for most accurate regridding
  gfs_physics_nml:
    disable_radiation_quasi_sea_ice: true  # Disable skin temperature dependent ocean albedo and emissivity
    fhlwr: 3600.0  # Use a radiation timestep of 3600 seconds
    fhswr: 3600.0  # Use a radiation timestep of 3600 seconds
    fhzero: 6.0  # Required for outputting physics diagnostics every six hours
    iaer: 11  # Run with only tropospheric SW and LW effect of aerosols (no volcanic aerosols)
    ico2: 1  # Run with spatially uniform carbon dioxide concentration
    ictm: 19970  # Required for perpetual 1997 carbon dioxide concentration
    imfdeepcnv: 3  # Use most up-to-date deep convection scheme to ensure stability
    imfshalcnv: 3  # Use shallow convection scheme version consistent with deep convection scheme
    use_ext_sst: true  # Required for running with prescribed SSTs and sea-ice
    co2_perturbation_exponent_minimum: -2.0  # Minimum scale factor of 0.25
    co2_perturbation_exponent_maximum: 2.0  # Maximum scale factor of 4.0
    co2_perturbation_period_seconds: 2592000  # Draw a new scale factor every 30 days
    co2_perturbation_random_seed: 20  # Make sure to use unique value per run
  namsfc:
    # Prevent updating certain variables during surface cycling, since
    # these should be controlled by the physics driver.
    faisl: 99999  # Surface type
    faiss: 99999  # Surface type
    fsicl: 99999  # Sea ice fraction
    fsics: 99999  # Sea ice fraction
    fsihl: 99999  # Sea ice height
    fsihs: 99999  # Sea ice height
    ftsfl: 99999  # Surface temperature
    ftsfs: 99999  # Surface temperature
diag_table:
  base_time: 2000-01-01 00:00:00
  name: full-model-emulation-training-data-run
  file_configs:
  - field_configs:
    - {module_name: dynamics, field_name: temp, output_name: air_temperature}
    - {module_name: dynamics, field_name: sphum, output_name: specific_humidity}
    - {module_name: dynamics, field_name: ucomp, output_name: eastward_wind}
    - {module_name: dynamics, field_name: vcomp, output_name: northward_wind}
    - {module_name: dynamics, field_name: delp_total, output_name: pressure_thickness_of_atmospheric_layer}
    - {module_name: dynamics, field_name: liq_wat, output_name: cloud_water_mixing_ratio}
    - {module_name: dynamics, field_name: ice_wat, output_name: cloud_ice_mixing_ratio}
    - {module_name: dynamics, field_name: rainwat, output_name: rain_mixing_ratio}
    - {module_name: dynamics, field_name: snowwat, output_name: snow_mixing_ratio}
    - {module_name: dynamics, field_name: graupel, output_name: graupel_mixing_ratio}
    - {module_name: dynamics, field_name: o3mr, output_name: ozone_mixing_ratio}
    - {module_name: gfs_sfc, field_name: SLMSKsfc, output_name: land_sea_mask}
    - {module_name: gfs_sfc, field_name: ocean_fraction, output_name: ocean_fraction}
    - {module_name: gfs_sfc, field_name: land_fraction, output_name: land_fraction}
    - {module_name: gfs_sfc, field_name: sea_ice_fraction, output_name: sea_ice_fraction}
    - {module_name: gfs_sfc, field_name: tsfc, output_name: surface_temperature}
    - {module_name: gfs_sfc, field_name: t2m, output_name: air_temperature_at_two_meters}
    - {module_name: gfs_sfc, field_name: q2m, output_name: specific_humidity_at_two_meters}
    - {module_name: gfs_phys, field_name: u10m, output_name: eastward_wind_at_ten_meters}
    - {module_name: gfs_phys, field_name: v10m, output_name: northward_wind_at_ten_meters}
    - {module_name: dynamics, field_name: zsurf, output_name: HGTsfc}  # Not geopotential, but that's in restart files
    - {module_name: gfs_phys, field_name: soilm, output_name: column_soil_moisture}
    - {module_name: gfs_sfc, field_name: SOILW1, output_name: soil_moisture_0}
    - {module_name: gfs_sfc, field_name: SOILW2, output_name: soil_moisture_1}
    - {module_name: gfs_sfc, field_name: SOILW3, output_name: soil_moisture_2}
    - {module_name: gfs_sfc, field_name: SOILW4, output_name: soil_moisture_3}
    - {module_name: gfs_sfc, field_name: fice, output_name: sea_ice_concentration}
    - {module_name: gfs_sfc, field_name: hice, output_name: sea_ice_thickness}
    - {module_name: dynamics, field_name: ps, output_name: PRESsfc}
    - {module_name: dynamics, field_name: slp, output_name: PRMSL}
    - {module_name: dynamics, field_name: rh200, output_name: RH200}
    - {module_name: dynamics, field_name: rh500, output_name: RH500}
    - {module_name: dynamics, field_name: rh850, output_name: RH850}
    - {module_name: dynamics, field_name: t200, output_name: TMP200}
    - {module_name: dynamics, field_name: t500, output_name: TMP500}
    - {module_name: dynamics, field_name: t850, output_name: TMP850}
    - {module_name: dynamics, field_name: u200, output_name: UGRD200}
    - {module_name: dynamics, field_name: u500, output_name: UGRD500}
    - {module_name: dynamics, field_name: u850, output_name: UGRD850}
    - {module_name: dynamics, field_name: u1000, output_name: UGRD1000}
    - {module_name: dynamics, field_name: v200, output_name: VGRD200}
    - {module_name: dynamics, field_name: v500, output_name: VGRD500}
    - {module_name: dynamics, field_name: v850, output_name: VGRD850}
    - {module_name: dynamics, field_name: v1000, output_name: VGRD1000}
    - {module_name: dynamics, field_name: z50, output_name: h50}
    - {module_name: dynamics, field_name: z200, output_name: h200}
    - {module_name: dynamics, field_name: z250, output_name: h250}
    - {module_name: dynamics, field_name: z300, output_name: h300}
    - {module_name: dynamics, field_name: z500, output_name: h500}
    - {module_name: dynamics, field_name: z700, output_name: h700}
    - {module_name: dynamics, field_name: z850, output_name: h850}
    - {module_name: dynamics, field_name: z1000, output_name: h1000}
    - {module_name: gfs_sfc, field_name: SOILT1, output_name: soil_temperature_0}
    - {module_name: gfs_sfc, field_name: SOILT2, output_name: soil_temperature_1}
    - {module_name: gfs_sfc, field_name: SOILT3, output_name: soil_temperature_2}
    - {module_name: gfs_sfc, field_name: SOILT4, output_name: soil_temperature_3}
    - {module_name: gfs_sfc, field_name: snowd, output_name: snow_depth}
    - {module_name: gfs_sfc, field_name: weasd, output_name: water_equivalent_snow_depth}
    - {module_name: gfs_sfc, field_name: snow_cover, output_name: snow_cover_fraction}
    name: full_state
    frequency: 6
    frequency_units: hours
    time_axis_name: time
    time_axis_units: hours
  - field_configs:
    - {module_name: dynamics, field_name: grid_latt, output_name: lat}
    - {module_name: dynamics, field_name: grid_lont, output_name: lon}
    - {module_name: dynamics, field_name: grid_lat, output_name: latb}
    - {module_name: dynamics, field_name: grid_lon, output_name: lonb}
    - {module_name: gfs_phys, field_name: DSWRF, output_name: DSWRFsfc}
    - {module_name: gfs_phys, field_name: DLWRF, output_name: DLWRFsfc}
    - {module_name: gfs_phys, field_name: USWRF, output_name: USWRFsfc}
    - {module_name: gfs_phys, field_name: ULWRF, output_name: ULWRFsfc}
    - {module_name: gfs_phys, field_name: DSWRFtoa, output_name: DSWRFtoa}
    - {module_name: gfs_phys, field_name: USWRFtoa, output_name: USWRFtoa}
    - {module_name: gfs_phys, field_name: ULWRFtoa, output_name: ULWRFtoa}
    - {module_name: gfs_phys, field_name: lhtfl_ave, output_name: LHTFLsfc}
    - {module_name: gfs_phys, field_name: shtfl_ave, output_name: SHTFLsfc}
    - {module_name: gfs_phys, field_name: totprcpb_ave, output_name: PRATEsfc}
    - {module_name: gfs_phys, field_name: toticeb_ave, output_name: ICEsfc}
    - {module_name: gfs_phys, field_name: totsnwb_ave, output_name: SNOWsfc}
    - {module_name: gfs_phys, field_name: totgrpb_ave, output_name: GRAUPELsfc}
    - {module_name: dynamics, field_name: tq, output_name: precipitable_water_path}
    - {module_name: dynamics, field_name: iw, output_name: ice_water_path}
    - {module_name: dynamics, field_name: lw, output_name: liquid_water_path}
    - {module_name: dynamics, field_name: te, output_name: total_energy}
    - {module_name: gfs_phys, field_name: dusfc, output_name: eastward_surface_wind_stress}
    - {module_name: gfs_phys, field_name: dvsfc, output_name: northward_surface_wind_stress}
    - {module_name: gfs_phys, field_name: gflux_ave, output_name: GHTFLsfc}
    name: fluxes_2d
    frequency: 6
    frequency_units: hours
    time_axis_name: time
    time_axis_units: hours
  - field_configs:
    - {module_name: dynamics, field_name: t_dt_diabatic, output_name: temperature_tendency_due_to_diabatic_processes, reduction_method: average}
    - {module_name: dynamics, field_name: qv_dt_diabatic, output_name: specific_humidity_tendency_due_to_diabatic_processes, reduction_method: average}
    - {module_name: gfs_phys, field_name: tendency_of_air_temperature_due_to_longwave_heating, output_name: tendency_of_air_temperature_due_to_longwave_heating, reduction_method: average}
    - {module_name: gfs_phys, field_name: tendency_of_air_temperature_due_to_shortwave_heating, output_name: tendency_of_air_temperature_due_to_shortwave_heating, reduction_method: average}
    name: tendencies_3d
    frequency: 6
    frequency_units: hours
    time_axis_name: time
    time_axis_units: hours
  - field_configs:
    # Technically CO2 is a "next step forcing" (whether interval-averaged or not) since it is time-labeled at the
    # endpoint of the interval it is forcing the atmosphere for. We therefore output it as an interval-average
    # diagnostic to make that clearer, and better-defined for 6-hour intervals (even though it never changes
    # within 6-hour intervals in our runs anyway).
    - {module_name: gfs_phys, field_name: global_mean_co2, output_name: global_mean_co2, reduction_method: average}
    name: scalar
    frequency: 6
    frequency_units: hours
    time_axis_name: time
    time_axis_units: hours
patch_files:  # Needed for running with prescribed SSTs and sea-ice
- copy_method: copy
  source_location: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/projects/2025-07-16-ramped-sst-simulations/shield_run/config
  source_name: data_table
  target_location: .
  target_name: data_table
- copy_method: copy
  source_location: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/reference/2025-07-16-climatological-ramped-sst-forcing-data
  source_name: climatological_sst_with_linear_ramp.nc
  target_location: INPUT/
  target_name: sst.nc
- copy_method: copy
  source_location: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/reference/2025-07-16-climatological-ramped-sst-forcing-data
  source_name: climatological_sea_ice.nc
  target_location: INPUT/
  target_name: sea_ice.nc
