config_name: 2025-08-22-SHiELD-SOM-C96-production-simulations

# Directories for storing output
# output_directory is for storing final products
# working_directory is for storing any temporary intermediates
# gcs_bucket is the root directory for any data uploaded to Google Cloud Storage
archive_directory: /archive/Spencer.Clark/2025-08-22-C96-SHiELD-SOM
output_directory: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/scratch/2025-08-22-C96-SHiELD-SOM-production-post-processing
working_directory: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/scratch/2025-08-22-C96-SHiELD-SOM-production-post-processing/work
gcs_bucket: gs://vcm-ml-raw-flexible-retention/2025-08-22-C96-SHiELD

# runs: a mapping from run names (for use in wildcards) to paths to run
# directories.
runs:
  ramped-sst-1xCO2-random-perturbation: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/scratch/2025-07-23-reference-SHiELD-runs/climatological-ramped-sst-1xCO2-C96-random-co2
  ramped-sst-2xCO2-random-perturbation: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/scratch/2025-07-23-reference-SHiELD-runs/climatological-ramped-sst-2xCO2-C96-random-co2
  ramped-sst-4xCO2-random-perturbation: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/scratch/2025-07-23-reference-SHiELD-runs/climatological-ramped-sst-4xCO2-C96-random-co2
  ramped-sst-1xCO2-random-perturbation-ic_0002: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/scratch/2025-07-23-reference-SHiELD-runs/climatological-ramped-sst-1xCO2-C96-random-co2-ic_0002
  ramped-sst-2xCO2-random-perturbation-ic_0002: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/scratch/2025-07-23-reference-SHiELD-runs/climatological-ramped-sst-2xCO2-C96-random-co2-ic_0002
  ramped-sst-4xCO2-random-perturbation-ic_0002: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/scratch/2025-07-23-reference-SHiELD-runs/climatological-ramped-sst-4xCO2-C96-random-co2-ic_0002
  ramped-sst-1xCO2-random-perturbation-ic_0003: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/scratch/2025-07-23-reference-SHiELD-runs/climatological-ramped-sst-1xCO2-C96-random-co2-ic_0003
  ramped-sst-2xCO2-random-perturbation-ic_0003: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/scratch/2025-07-23-reference-SHiELD-runs/climatological-ramped-sst-2xCO2-C96-random-co2-ic_0003
  ramped-sst-4xCO2-random-perturbation-ic_0003: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/scratch/2025-07-23-reference-SHiELD-runs/climatological-ramped-sst-4xCO2-C96-random-co2-ic_0003

# cubed_sphere_grid_data: a mapping from resolutions to paths to mosaic files
# for cubed sphere grids.
cubed_sphere_grid_data:
  C24: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/reference/2024-06-19-vcm-fv3config/data/grid_data/v1.2/C24/C24_mosaic.nc
  C48: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/reference/2024-06-19-vcm-fv3config/data/grid_data/v1.2/C48/C48_mosaic.nc
  C96: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/reference/2024-06-19-vcm-fv3config/data/grid_data/v1.2/C96/C96_mosaic.nc

# target_grid_data: a mapping from target grid names (for use in wildcards) to
# paths to mosaic files for output grids.
target_grid_data:
  gaussian_grid_180_by_360:
    mosaic: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/reference/2024-01-29-gaussian-grid-mosaics/gaussian_grid_180_by_360/gaussian_grid_180_by_360_mosaic.nc
    chunks:
      scalar:
        time: -1
      2D:
        time: 160
      3D:
        time: 16
        pfull: 10
  gaussian_grid_45_by_90:
    mosaic: /gpfs/f5/gfdl_w/scratch/Spencer.Clark/reference/2024-01-29-gaussian-grid-mosaics/gaussian_grid_45_by_90/gaussian_grid_45_by_90_mosaic.nc
    chunks:
      scalar:
        time: -1
      2D:
        time: 2560
      3D:
        time: 256
        pfull: 10

# Number of ranks to partition combine jobs over
xpartition_ranks: 30

# Chunk sizes for opening the netCDF files initially
initial_chunks:
  time: 16

# Configure the spherical harmonic transformation roundtrip
spherical_harmonic_transform_filter:
  filter_data: True
  unfiltered_variables:
  - land_sea_mask
  - ocean_fraction
  - land_fraction
  - sea_ice_fraction
  - column_soil_moisture
  - soil_moisture_0
  - soil_moisture_1
  - soil_moisture_2
  - soil_moisture_3
  - soil_temperature_0
  - soil_temperature_1
  - soil_temperature_2
  - soil_temperature_3
  - snow_depth
  - water_equivalent_snow_depth
  - snow_cover_fraction
  - sea_ice_concentration
  - sea_ice_thickness
